# Generated by Django 5.1 on 2024-08-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_remove_cliente_telefone_cliente_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
