# Generated by Django 5.1 on 2024-08-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_cliente_password_alter_cliente_whatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_plano', models.CharField(max_length=255)),
                ('qtdade_ativos', models.IntegerField()),
                ('periodicidade', models.IntegerField()),
                ('email', models.BooleanField()),
                ('whatsapp', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='acao',
        ),
        migrations.DeleteModel(
            name='Acao',
        ),
        migrations.DeleteModel(
            name='Noticia',
        ),
    ]
