# Generated by Django 5.1 on 2024-08-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_planos_remove_noticia_acao_delete_acao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_plano', models.CharField(max_length=255)),
                ('qtdade_ativos', models.IntegerField()),
                ('qtdade_noticias', models.IntegerField()),
                ('periodicidade', models.IntegerField()),
                ('email', models.BooleanField()),
                ('whatsapp', models.BooleanField()),
                ('tempo_real', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Planos',
        ),
    ]
