# Generated by Django 5.1 on 2024-08-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_plano_delete_planos'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='valor',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
