# Generated by Django 5.1 on 2024-08-14 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0011_alter_cliente_plano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='plano',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='noticias.plano'),
        ),
    ]
