# Generated by Django 5.1 on 2024-08-14 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0012_alter_cliente_plano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='plano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='noticias.plano'),
        ),
    ]
