# Generated by Django 5.1 on 2024-08-16 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0014_dadospagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadospagamento',
            name='data_renovacao_plano',
            field=models.DateField(blank=True, null=True),
        ),
    ]
