# Generated by Django 5.1 on 2024-08-16 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0015_dadospagamento_data_renovacao_plano'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dadospagamento',
            options={},
        ),
    ]
