# Generated by Django 5.1 on 2024-08-16 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0016_alter_dadospagamento_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dadospagamento',
            options={'verbose_name': 'Dados de Pagamento', 'verbose_name_plural': 'Dados de Pagamento'},
        ),
    ]
