# Generated by Django 5.1 on 2024-08-16 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0017_alter_dadospagamento_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dadospagamento',
            name='cvv',
        ),
    ]
