# Generated by Django 5.1 on 2024-08-17 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0018_remove_dadospagamento_cvv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acaoselecionada',
            options={'verbose_name': 'Tickers selecionados', 'verbose_name_plural': 'Tickers selecionados'},
        ),
        migrations.AlterModelOptions(
            name='plano',
            options={'verbose_name': 'Planos disponíveis', 'verbose_name_plural': 'Planos disponíveis'},
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonte', models.CharField(max_length=255)),
                ('conteudo', models.TextField(blank=True, null=True)),
                ('acao_selecionada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticias', to='noticias.acaoselecionada')),
            ],
        ),
    ]
