# Generated by Django 5.1 on 2024-08-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0019_alter_acaoselecionada_options_alter_plano_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
