# Generated by Django 5.1 on 2024-08-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0020_noticia_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='data_publicacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
