# Generated by Django 5.0.7 on 2024-08-17 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0021_noticia_data_publicacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acaoselecionada',
            old_name='nome',
            new_name='setor',
        ),
    ]
