# Generated by Django 5.0.7 on 2024-08-17 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0022_rename_nome_acaoselecionada_setor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acaoselecionada',
            options={'verbose_name': 'Ticker selecionado', 'verbose_name_plural': 'Tickers selecionados'},
        ),
        migrations.AlterModelOptions(
            name='plano',
            options={'verbose_name': 'Plano disponível', 'verbose_name_plural': 'Planos disponíveis'},
        ),
        migrations.RenameField(
            model_name='acaoselecionada',
            old_name='setor',
            new_name='nome',
        ),
    ]
