# Generated by Django 5.1 on 2024-08-19 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0023_alter_acaoselecionada_options_alter_plano_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadospagamento',
            old_name='data_renovacao_plano',
            new_name='data_renovacao_pagamento',
        ),
    ]
