# Generated by Django 5.1 on 2024-08-21 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0025_alter_dadospagamento_numero_cartao_alter_plano_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
