# Generated by Django 5.0.7 on 2024-08-26 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0027_delete_dadospagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.CharField(blank=True, max_length=255, null=True)),
                ('data_criacao', models.DateTimeField(blank=True, null=True)),
                ('data_expiracao', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='noticias.token'),
        ),
    ]
