# Generated by Django 5.0.7 on 2024-08-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0028_token_cliente_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token_id',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
