# Generated by Django 5.1 on 2024-09-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0030_alter_cliente_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acaoselecionada',
            name='cliente',
        ),
        migrations.AddField(
            model_name='cliente',
            name='tickers',
            field=models.ManyToManyField(related_name='clientes', to='noticias.acaoselecionada'),
        ),
    ]
