# Generated by Django 5.1 on 2024-09-06 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0033_alter_adress_options_cliente_cpf_alter_adress_cep'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adress',
            new_name='Endereco',
        ),
    ]
