# Generated by Django 5.1 on 2024-09-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0034_rename_adress_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='acaoselecionada',
            name='volume',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
