# Generated by Django 5.1 on 2024-09-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0035_acaoselecionada_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='data_geracao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='resumo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
