# Generated by Django 5.1 on 2024-09-16 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0036_noticia_data_geracao_noticia_resumo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='data_geracao',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='resumo',
        ),
    ]
